ame: Deploy via SFTP

on:
  pull_request:
    branches:
      - main

jobs:
  sftp-deploy:
    runs-on: debian-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './'
          remote_path: '/var/www/portfolio/'
          sftp_only: 'true'
          exclude: |
            .git*
            node_modules
            README.md
            .env